# Generated by Django 4.2.7 on 2023-11-08 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Paper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=100)),
                ('Subject', models.CharField(max_length=80)),
                ('Duration', models.IntegerField()),
                ('Instructions', models.TextField(null=True)),
                ('TotalMarks', models.IntegerField(default=0)),
                ('TeacherName', models.CharField(max_length=100)),
                ('Class', models.CharField(max_length=50)),
            ],
        ),
    ]
